#!/bin/sh

create_virtualenv() {
    local env_directory="$HOME/env"

    if [ ! -d $env_directory ] ; then
        virtualenv $env_directory
		. $env_directory/bin/activate
        pip install pip --upgrade
    fi
}

install_dependencies() {
    local download_cache="$HOME/.pip/downloads/"

    if [ -f requirements.txt ] ; then
        [ -d $download_cache ] || mkdir -p $download_cache
        pip install --download-cache=$download_cache -r requirements.txt
    fi
}

install_application() {
    rsync -aH --delete --exclude "data" * $HOME/
}

create_virtualenv
install_dependencies
install_application
